'''# example 1 = program for write mode f1=open('sanjay.txt','w')
f1=open("sanjay.txt","w")
f1.writelines("this is my laptop")
f1.close()

# example 2 = program for read mode f1=open('sanjay.txt','r')
with open("sanjay.txt","r") as f1:
    text=f1.read()
print(text)
# example 3 = program for append mode f1=open('sanjay.txt','a')
f1=open("sanjay.txt","a")
f1.writelines("\n where is your bag")
f1.close()
'''
# example 4 = program for write mode f2=open('student.txt','w')
f2=open("student.txt","a")
f2.writelines("Name\t""Grade\t""Rollnumber\n")
Name=input("Enter your name =")
Grade=input("Enter your grade =")
Rollnumber=input("enter your roll number =")
f2.writelines(Name+"\t")
f2.writelines(Grade+"\t\t")
f2.writelines(Rollnumber+"\t")
f2.close()